### PR TITLE
Build binary for Linux ppc64le

### PR DESCRIPTION
**Pull request by runlevel5**
## WHAT

Produce binary for Linux ppc64le

## WHY

Because many people are using k8s that runs on IBM POWER9 CPU

## Related issue (if exists)

N/A

### CODE REVIEW

**Comment by dty1er** [comment]
@runlevel5 
Hi, thank you for sending this PR. Let me ask a question about this PR.

Do you want to use kubecolor installed on IBM POWER9 CPU machine? Even if you are running kubernetes on IBM POWER9 CPU machine but you run kubectl on your client machine (e.g. your laptop), then kubecolor does not need need to support ppc64le because kubecolor itself runs on your client machine.

**Comment by dty1er** [comment]
@runlevel5 
Another question is, are bash/zsh be able to be used on the machine? Because kubecolor uses ANSI escape code to colorize things, the shell must support it to use kubecolor on it.

**Comment by runlevel5** [comment]
> Do you want to use kubecolor installed on IBM POWER9 CPU machine? Even if you are running kubernetes on IBM POWER9 CPU machine but you run kubectl on your client machine (e.g. your laptop), then kubecolor does not need need to support ppc64le because kubecolor itself runs on your client machine.

Yes I do want to run kubecolour on my box. Atm I am using kubectl (ppc64le) to access to my K8S hosted in AWS EKS. 

> Another question is, are bash/zsh be able to be used on the machine? Because kubecolor uses ANSI escape code to colorize things, the shell must support it to use kubecolor on it.

I am using bash

**Comment by dty1er** [comment]
@runlevel5 
OK, thanks

**Review by dty1er — APPROVED** [review]

**Pull request merged**
